services:
  postgres:
    image: postgres:15
    container_name: shreekamalinee_db
    restart: always
    environment:
      POSTGRES_DB: shreekamalinee_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Kolkata
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d shreekamalinee_db"]
      interval: 3s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: shreekamalinee_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: shreekamalinee
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/shreekamalinee_db
      - REDIS_HOST=redis
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env

volumes:
  pgdata:
  redisdata: